apiVersion: v1
kind: Service
metadata:
  name: novapay-payment-gateway
  namespace: default
  labels:
    app: novapay-payment-gateway
spec:
  selector:
    app: novapay-payment-gateway
  ports:
  - name: http
    port: 80
    targetPort: 5000
  type: ClusterIP