apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: novapay-payment-gateway
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
    - novapay
  selector:
    matchLabels:
      app: novapay-payment-gateway
  endpoints:
  - port: http
    path: /metrics
    interval: 15s