apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-payment-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-payment-gateway
spec:
  selector:
    app: {{ .Release.Name }}-payment-gateway
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}

